version: '3.8'

services:
  backend:
    build:
      context: ./task-manager
    container_name: task-manager-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./task-manager-ui
    container_name: task-manager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
